version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Oslo"
    # Samme som minimumReleaseAge i pnpm-workspace.yaml
    cooldown:
      default-days: 3
      exclude:
        - "@navikt/*"
    versioning-strategy: "auto"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "pnpm"
    commit-message:
      prefix: "chore"
      include: "scope"
    registries:
      - navikt-npm
    groups:
      minor-og-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      major:
        patterns:
          - "*"
        update-types:
          - "major"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Oslo"
    cooldown:
      default-days: 3
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      github-actions:
        patterns:
          - "*"

# Define the registry
registries:
  navikt-npm:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{ secrets.READER_TOKEN }}