apiVersion: nais.io/v1alpha1
kind: Application
metadata:
    name: vis-stilling
    namespace: default
    labels:
        team: arbeidsgiver
spec:
    image: {{ image }}
    port: 3000
    ingresses:
        - https://www-q0.nav.no/arbeid/stilling
    liveness:
        initialDelay: 5
        path: /arbeid/stilling/internal/isAlive
    readiness:
        initialDelay: 5
        path: /arbeid/stilling/internal/isReady
    vault:
        enabled: true
        paths:
            # Managed secrets
            - kvPath: /apikey/apigw/dev/rekrutteringsbistand-sms/vis-stilling
              mountPath: /var/run/secrets/nais.io/vault
    env:
        - name: APIGW_URL
          value: https://api-gw-q1.oera.no
