apiVersion: nais.io/v1alpha1
kind: Application
metadata:
    name: vis-stilling
    namespace: arbeidsgiver
    labels:
        team: arbeidsgiver
spec:
    image: {{ image }}
    port: 3000
    ingresses:
        - https://www.nav.no/arbeid/stilling
    liveness:
        initialDelay: 5
        path: /arbeid/stilling/internal/isAlive
    readiness:
        initialDelay: 5
        path: /arbeid/stilling/internal/isReady
    azure:
        application:
            enabled: true
    accessPolicy:
        outbound:
            external:
                - host: rekrutteringsbistand-stilling-api.prod-fss-pub.nais.io
                - host: dekoratoren.nav.no
    env:
        - name: REKRUTTERINGSBISTAND_STILLING_API
          value: https://rekrutteringsbistand-stilling-api.prod-fss-pub.nais.io
