apiVersion: nais.io/v1alpha1
kind: Application
metadata:
    name: vis-stilling
    namespace: default
    labels:
        team: arbeidsgiver
spec:
    image: {{ image }}
    port: 3000
    ingresses:
        - https://www-q0.nav.no/arbeid/stilling
    liveness:
        initialDelay: 5
        path: /arbeid/stilling/internal/isAlive
    readiness:
        initialDelay: 5
        path: /arbeid/stilling/internal/isReady
    vault:
        enabled: true
        paths:
            - kvPath: /apikey/apigw/dev/rekrutteringsbistand-api/vis-stilling_q1
              mountPath: /secret/apigw
    env:
        - name: APIGW_URL
          value: https://api-gw-q1.oera.no
