apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
    name: vis-stilling
    namespace: toi
    labels:
        team: toi
spec:
    groups:
        - name: vis-stilling
          rules:
              - alert: vis-stilling
                expr: kube_deployment_status_replicas_available{deployment="vis-stilling"} == 0
                for: 1s
                annotations:
                    summary: Appen er nede
                    action: 'https://logs.adeo.no/app/r/s/LFtib'
                labels:
                    namespace: toi
                    severity: critical

              - alert: vis-stilling
                expr: sum(increase(log_messages_errors{app="vis-stilling", level="Error"}[10m])) > 0
                for: 1s
                annotations:
                    summary: Appen har logget en error
                    action: 'https://logs.adeo.no/app/r/s/LFtib'
                labels:
                    namespace: toi
                    severity: critical

              - alert: vis-stilling
                expr: sum(increase(log_messages_errors{app="vis-stilling", level="Warning"}[10m])) > 3
                for: 1s
                annotations:
                    summary: Økning i warnings
                    action: 'https://logs.adeo.no/app/r/s/LFtib'
                labels:
                    namespace: toi
                    severity: warning
