apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  labels:
    team: toi
  name: vis-stilling-veileder
  namespace: toi
spec:
  replicas:
    max: 4
    min: 2
  image: {{ image }}
  ingresses:
    - {{ NEXT_PUBLIC_BASE_URL }}
  port: 3000
  liveness:
    initialDelay: 5
    path: /arbeid/stilling/internal/isAlive
  readiness:
    initialDelay: 5
    path: /arbeid/stilling/internal/isReady
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        groups:
          - id: {{ adGruppeModiaOppfolgg }}
        extra:
          - NAVident
    sidecar:
      enabled: true
      autoLogin: true
  tokenx:
    enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: rekrutteringsbistand-stilling-api
          namespace: toi
        - application: toi-deling-av-cv-api
        - application: modiacontextholder
          namespace: personoversikt
  env:
    - name: ER_VEILEDER
      value: "true"
    - name: NEXT_PUBLIC_BASE_URL
      value: {{ NEXT_PUBLIC_BASE_URL }}
    - name: STILLING_API
      value: http://rekrutteringsbistand-stilling-api
    - name: TOI_DELING_AV_CV_API
      value: http://toi-deling-av-cv-api
    - name: MODIA_CONTEXT_HOLDER_API
      value: http://modiacontextholder.personoversikt
    - name: NEXT_PUBLIC_DECORATOR_SRC
      value: {{ decoratorSrc }}
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
    logging:
      destinations:
        - id: loki
        - id: elastic
      enabled: true
