name: Dependabot pnpm-lockfile

on:
    pull_request:
        branches: [main]
        paths:
            - '**/package.json'
            - 'pnpm-lock.yaml'

jobs:
    lockfile:
        name: 🤖
        uses: navikt/toi-frontend-workflows/.github/workflows/dependabot-pnpm.yaml@v3.1
        secrets: inherit
        permissions:
            contents: write
